export const SET_FAVORITE = 'SET_FAVORITE';
export const RMV_FAVORITE = 'RMV_FAVORITE';
export const TOGGLE_TEMP = 'TOGGLE_TEMP';
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const SET_SELECTED_PLACE = 'SET_SELECTED_PLACE';
export const SET_FAVORITES_FROM_STORGE = 'SET_FAVORITES_FROM_STORGE'
